language: node_js
node_js:
  - "8"
sudo: required
branches:
  only:
    - master
    - /^greenkeeper/.*$/
dist: trusty

install:
  - npm i -g npm@5.7.1 # this should be deleted once 5.7.X is out of "pre-release"
  - npm ci             # instead of default npm install 

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e
